version: '3'
services:
  gerrit1:
    build: .
    environment:
      - INSTANCE_ID=primary
      - REPLICA=false
      - REMOTE=replica-1
      - REMOTE_URL=gerrit2
      - DEBUG_PORT=5005
      - REPLICATE_ON_STARTUP=false
      - MIRROR=true
    ports:
      - "8080:8080"
      - "29418:29418"
      - "5005:5005"
  gerrit2:
    build: .
    environment:
      - INSTANCE_ID=replica-1
      - REPLICA=true
      - REMOTE=primary
      - REMOTE_URL=gerrit1
      - DEBUG_PORT=5006
      - REPLICATE_ON_STARTUP=true
      - MIRROR=true
    ports:
      - "8081:8080"
      - "29419:29418"
      - "5006:5006"
    depends_on:
      - gerrit1
