version: '3'
services:
  gerrit1:
    build: .
    environment:
      - INSTANCE_ID=primary
      - REPLICA=false
      - REMOTE=replica-1
      - REMOTE_URL=gerrit2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/config/server/healthcheck~status"]
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
      - "29418:29418"
  gerrit2:
    build: .
    environment:
      - INSTANCE_ID=replica-1
      - REPLICA=true
      - REMOTE=primary
      - REMOTE_URL=gerrit1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/config/server/healthcheck~status"]
      start_period: 120s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8081:8080"
      - "29419:29418"
    depends_on:
      - gerrit1

# volumes:
#   gerrit1_git:
#   gerrit2_git: